# Generated by Django 6.0.3 on 2026-05-29 11:21

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='banners/')),
                ('button_text', models.CharField(default='Book Now', max_length=40)),
                ('button_link', models.CharField(default='/', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Cab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('city', models.CharField(max_length=80)),
                ('vehicle_type', models.CharField(choices=[('mini', 'Mini'), ('sedan', 'Sedan'), ('suv', 'SUV'), ('tempo', 'Tempo Traveller')], max_length=20)),
                ('seats', models.PositiveIntegerField(default=4)),
                ('base_fare', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_per_km', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='cabs/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['city', 'base_fare'],
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=130)),
                ('city', models.CharField(max_length=80)),
                ('address', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rooms_available', models.PositiveIntegerField(default=10)),
                ('rating', models.DecimalField(decimal_places=1, default=4.0, max_digits=3)),
                ('image', models.ImageField(blank=True, null=True, upload_to='hotels/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['city', 'price_per_night'],
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('offer_type', models.CharField(choices=[('flight', 'Flight'), ('bus', 'Bus'), ('train', 'Train'), ('tour', 'Tour'), ('hotel', 'Hotel'), ('cab', 'Cab')], max_length=20)),
                ('description', models.TextField()),
                ('discount_text', models.CharField(help_text='Example: FLAT 10% OFF', max_length=80)),
                ('coupon_code', models.CharField(blank=True, max_length=30)),
                ('image', models.ImageField(blank=True, null=True, upload_to='offers/')),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['offer_type', 'title'],
            },
        ),
        migrations.CreateModel(
            name='TravelService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('flight', 'Flight'), ('bus', 'Bus'), ('train', 'Train'), ('tour', 'Tour')], max_length=20)),
                ('title', models.CharField(max_length=140)),
                ('operator_name', models.CharField(max_length=100)),
                ('source', models.CharField(max_length=80)),
                ('destination', models.CharField(max_length=80)),
                ('departure_date', models.DateField()),
                ('departure_time', models.TimeField()),
                ('arrival_date', models.DateField()),
                ('arrival_time', models.TimeField()),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_seats', models.PositiveIntegerField(default=40)),
                ('seat_columns', models.PositiveIntegerField(default=4, help_text='Use 4 for bus/flight style, 6 for train style')),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['departure_date', 'departure_time'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_type', models.CharField(choices=[('travel', 'Flight/Bus/Train/Tour'), ('hotel', 'Hotel'), ('cab', 'Cab')], max_length=20)),
                ('pnr', models.CharField(blank=True, max_length=15, unique=True)),
                ('travellers', models.PositiveIntegerField(default=1)),
                ('selected_seats', models.JSONField(blank=True, default=list)),
                ('check_in', models.DateField(blank=True, null=True)),
                ('check_out', models.DateField(blank=True, null=True)),
                ('rooms', models.PositiveIntegerField(default=1)),
                ('pickup_location', models.CharField(blank=True, max_length=150)),
                ('drop_location', models.CharField(blank=True, max_length=150)),
                ('pickup_date', models.DateField(blank=True, null=True)),
                ('distance_km', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='confirmed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('cab', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.cab')),
                ('hotel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.hotel')),
                ('travel_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.travelservice')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('method', models.CharField(default='Demo Payment Gateway', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='success', max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=30)),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='booking.booking')),
            ],
        ),
    ]
