# Generated by Django 6.0.3 on 2026-06-24 13:45

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_booking_payment_status_alter_booking_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('country', models.CharField(default='India', max_length=80)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='destinations/')),
                ('starting_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('is_featured', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=220)),
                ('answer', models.TextField()),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['display_order', 'question'],
            },
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='myTrip Global', max_length=100)),
                ('logo_text', models.CharField(default='myTrip', max_length=40)),
                ('tagline', models.CharField(default='One stop travel shop', max_length=180)),
                ('hero_title', models.CharField(default='Book flights, hotels, tours and cabs in one place', max_length=180)),
                ('hero_subtitle', models.TextField(default='Search routes, select seats, choose tour packages and pay securely online.')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('support_email', models.EmailField(blank=True, max_length=254)),
                ('support_phone', models.CharField(blank=True, max_length=25)),
                ('footer_about', models.TextField(default='Dynamic Django travel booking system with admin-managed content.')),
                ('instagram_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('facebook_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Setting',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='TourPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('destination', models.CharField(max_length=120)),
                ('country', models.CharField(default='India', max_length=80)),
                ('category', models.CharField(choices=[('family', 'Family'), ('honeymoon', 'Honeymoon'), ('adventure', 'Adventure'), ('pilgrimage', 'Pilgrimage'), ('weekend', 'Weekend'), ('international', 'International')], default='family', max_length=30)),
                ('duration_days', models.PositiveIntegerField(default=3)),
                ('duration_nights', models.PositiveIntegerField(default=2)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('price_per_person', models.DecimalField(decimal_places=2, max_digits=10)),
                ('seats_available', models.PositiveIntegerField(default=20)),
                ('short_description', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('highlights', models.TextField(blank=True, help_text='Add one highlight per line.')),
                ('itinerary', models.TextField(blank=True, help_text='Add day-wise itinerary. One item per line is shown as a step.')),
                ('inclusions', models.TextField(blank=True, help_text='Add one inclusion per line.')),
                ('exclusions', models.TextField(blank=True, help_text='Add one exclusion per line.')),
                ('image', models.ImageField(blank=True, null=True, upload_to='tours/')),
                ('is_featured', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['price_per_person', 'destination'],
            },
        ),
        migrations.AlterModelOptions(
            name='banner',
            options={'ordering': ['display_order', '-created_at']},
        ),
        migrations.AddField(
            model_name='banner',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='special_requests',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='tour_travel_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='button_link',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='offer',
            name='button_text',
            field=models.CharField(default='Book Now', max_length=40),
        ),
        migrations.AddField(
            model_name='payment',
            name='cashfree_order_id',
            field=models.CharField(blank=True, db_index=True, max_length=80),
        ),
        migrations.AddField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='gateway_response',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_session_id',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_type',
            field=models.CharField(choices=[('travel', 'Flight/Bus/Train'), ('tour', 'Tour Package'), ('hotel', 'Hotel'), ('cab', 'Cab')], max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Payment'), ('paid', 'Paid / Confirmed'), ('failed', 'Payment Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(default='Cashfree', max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='travelservice',
            name='service_type',
            field=models.CharField(choices=[('flight', 'Flight'), ('bus', 'Bus'), ('train', 'Train'), ('tour', 'Tour Transport')], max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='tour_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.tourpackage'),
        ),
    ]
