# Generated by Django 6.0.3 on 2026-06-24 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_footerlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='footer_about',
            field=models.TextField(default='Book flights, buses, trains, tour packages, hotels and cabs from one trusted travel platform.'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='hero_subtitle',
            field=models.TextField(default='Search travel, select seats, choose packages and pay securely online with Cashfree.'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='hero_title',
            field=models.CharField(default='Book flights, buses, trains, hotels, tours and cabs in one place', max_length=180),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='tagline',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='travelservice',
            name='service_type',
            field=models.CharField(choices=[('flight', 'Flight'), ('bus', 'Bus'), ('train', 'Train')], max_length=20),
        ),
    ]
